project_name: trellis
version: 2
before:
  hooks:
  - go mod download
builds:
- env:
    - CGO_ENABLED=0
  ldflags:
    - -X main.updaterRepo=roots/trellis-cli
    - -X main.version={{ .Version }}
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm64
archives:
- name_template: >-
    {{ .ProjectName }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
  format_overrides:
    - goos: windows
      formats: ['zip']
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
sboms:
  - artifacts: archive
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - name: trellis-cli
    repository:
      owner: roots
      name: homebrew-tap
    directory: Formula
    homepage:  https://roots.io/trellis
    description: A CLI to manage Trellis projects
    install: |
      bin.install "trellis"
    test: |
      system "#{bin}/trellis --autocomplete-install"
      system "#{bin}/trellis -v"
