images:
- location: "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img"
  arch: "x86_64"
- location: "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-arm64.img"
  arch: "aarch64"
portForwards:
- guestPort: 80
  hostPort: 63389
containerd:
  user: false
provision:
- mode: user
  script: |
    #!/bin/bash
    set -eux -o pipefail
    sudo mkdir /home/web/.ssh
    sudo cp ~/.ssh/authorized_keys /home/web/.ssh/authorized_keys
    sudo chown -R web:web /home/web/.ssh
- mode: system
  script: |
    #!/bin/bash
    set -eux -o pipefail
    useradd web -m -d /home/web -G www-data -s /bin/bash
    echo "web ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/trellis-web-user
    mkdir -p /srv/www/{{ .SiteName }}/current
    chown web:www-data /srv/www/{{ .SiteName }}/current
