vmType: "vz"
images:
{{ range $image := .Config.Images -}}
- location: {{ $image.Location }}
  arch: {{ $image.Arch }}
{{ end }}
mounts:
{{ range $siteName, $site := .Sites -}}
- location: {{ $site.AbsLocalPath }}
  mountPoint: /srv/www/{{ $siteName }}/current
  writable: true
{{ end }}
mountType: "virtiofs"
networks:
- vzNAT: true
portForwards:
{{ range $port := .Config.PortForwards -}}
- guestPort: {{ $port.GuestPort}}
  hostPort: {{ $port.HostPort }}
{{ end }}
containerd:
  user: false
