name: goreleaser

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions: {}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - uses: anchore/sbom-action/download-syft@v0
      - name: GoReleaser release
        uses: goreleaser/goreleaser-action@v7
        with:
          version: '~> v2'
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_ACCESS_TOKEN }}
      - uses: actions/attest@v4
        with:
          subject-checksums: ./dist/trellis_checksums.txt
